//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vacancy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət Haqqında.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsumun keçidlərində bir çox dəyişiklik mövcuddur, lakin əksəriyyəti inyeksiya edilmiş yumorla bəzi formada dəyişikliyə məruz qalmışdır..
        /// </summary>
        public static string AboutFoot {
            get {
                return ResourceManager.GetString("AboutFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namizəd.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakansiya Kodu.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət Ünvanı.
        /// </summary>
        public static string CompAddress {
            get {
                return ResourceManager.GetString("CompAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CompEmail {
            get {
                return ResourceManager.GetString("CompEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət Adı.
        /// </summary>
        public static string CompName {
            get {
                return ResourceManager.GetString("CompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə Əlaqə.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə Məlumatları.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizə Yazın.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmə tarixi.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətraflı.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ən son xəbərlərimiz və Xüsusi təkliflərimiz barədə e-poçt yeniləmələrini əldə edin. Spam göndərmirik, buna görə narahat olmayın..
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt adresi.....
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təcrübə.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abunə.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Səhifə.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat.
        /// </summary>
        public static string Informasiya {
            get {
                return ResourceManager.GetString("Informasiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş təsviri.
        /// </summary>
        public static string JobDesc {
            get {
                return ResourceManager.GetString("JobDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Siyahısı.
        /// </summary>
        public static string JobListed {
            get {
                return ResourceManager.GetString("JobListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakansiya Haqqında.
        /// </summary>
        public static string JobSummary {
            get {
                return ResourceManager.GetString("JobSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Rejimi.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv Vakansiya.
        /// </summary>
        public static string Livejob {
            get {
                return ResourceManager.GetString("Livejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir xəta baş verdi Zəhmət olmasa biraz sonra yenidən cəhd edin.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız uğurla göndərilmişdir. Təşəkkür edirik!.
        /// </summary>
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxşar Vakansiyalar.
        /// </summary>
        public static string Oxsar {
            get {
                return ResourceManager.GetString("Oxsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakansiya Elan et.
        /// </summary>
        public static string PostJob {
            get {
                return ResourceManager.GetString("PostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklənmə Tarixi.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tərcümeyi hal.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaş.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndər.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xidmətlərimiz.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya Seçin.
        /// </summary>
        public static string SetCategory {
            get {
                return ResourceManager.GetString("SetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər Seçin.
        /// </summary>
        public static string SetLocation {
            get {
                return ResourceManager.GetString("SetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göstərilir.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vebsite.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizə Abunə Olun.
        /// </summary>
        public static string SubscribeUs {
            get {
                return ResourceManager.GetString("SubscribeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnyor Şirkətlər.
        /// </summary>
        public static string TopCompanies {
            get {
                return ResourceManager.GetString("TopCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətrafınızdakı minlərlə iş, məşğulluq və karyera imkanlarını tapmaq üçün pulsuz vakansiya elanı yükləyin!.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faydalı Linklər.
        /// </summary>
        public static string UsefulLİnks {
            get {
                return ResourceManager.GetString("UsefulLİnks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakansiyalar.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namizədinizi tapmaq üçün.
        /// </summary>
        public static string VacancyTitle {
            get {
                return ResourceManager.GetString("VacancyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad və Soyadınızı daxil edin.
        /// </summary>
        public static string Validate1 {
            get {
                return ResourceManager.GetString("Validate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt boş ola bilməz.
        /// </summary>
        public static string Validate2 {
            get {
                return ResourceManager.GetString("Validate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj başlığını doldurun.
        /// </summary>
        public static string Validate3 {
            get {
                return ResourceManager.GetString("Validate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj bölməsini doldurun.
        /// </summary>
        public static string Validate4 {
            get {
                return ResourceManager.GetString("Validate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açar söz.
        /// </summary>
        public static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
    }
}
